api:
  address: "localhost:8000"
mongo:
  host: "192.168.235.26"
  port: 27017
  db: crawlab_local
  username: "root"
  password: "example"
  authSource: "admin"
redis:
  address: 192.168.235.0
  password: redis-1.0
  database: 29
  port: 16379
log:
  level: info
  path: "/logs/crawlab"
server:
  host: 0.0.0.0
  port: 8000
  master: "Y"
  secret: "crawlab"
  register:
    # mac 或者 ip，如果是ip，则需要手动指定IP
    type: "mac"
    ip: "192.168.0.104"
spider:
  path: "/spiders"
task:
  workers: 4
other:
  tmppath: "/tmp"
